app/urls.py
from django.urls import include, path
from .views import general, customer, bike

urlpatterns = [

    path('', general.FrontPage, name='front_page'),
    
    path('logout', general.logout_user, name='user_logout'),
    path("login", general.login, name='userlogin'),
    path('vendorbytype/<name>/', general.AllVendor, name='all-vendors-type'),
    path('blogdetails/<slug>/', general.BlogDetails, name='post-detail'),
    
    


    path('bike/', include(([

        path('dashboard', bike.BikeDashboard, name='dashboard'),
        path('profile/<pk>', bike.BikeProfile, name='bike_profile'),
        path('orders', bike.DeliveryOrder, name='order_delivery'),
        path('ordersdetails/<pk>', bike.DetailsOrder, name='details'),
        path('orderaccept/<pk>', bike.AcceptOrder, name='accept-order'),
        path('ongoingmessage/<pk>/', bike.OnGoingOrder, name='order-ongoing'),
        
        
        path('packagecompleted/<pk>', bike.CompleteOrder, name='package-complete'),
        path('cancelpackage/<pk>', bike.CancelOrder, name='cancel-package'),
        
        path('messageaccept/<pk>/', bike.AcceptPackage, name='accept-message'),
        path('ongoingmessage/<pk>/', bike.OnGoingPackage, name='message-ongoing'),
        path('ongoingmessagedetails/<pk>/', bike.OnGoingPackageDetails, name='message-ongoing-details'),

      


   
      
    ], 'app'), namespace='bike')),

    path('customer/', include(([

        path('dashboard', customer.CustomerDashboard, name='dashboard'),
        path('profile/<pk>', customer.CustomerProfile, name='customer_profile'),
        path('vendors/', customer.AllRestaurants, name='all-vendor'),
        path('vendorgood/<pk>/', customer.AllVendorGoods, name='all-vendors-good'),

        path('menu/', customer.AllMenu, name='all-menu'),

        path('foodgeneral/<name>/', general.FoodDetails, name='food-general'),


        path('mycart/<pk>/', customer.add_to_cart, name='add-to-cart'),
        path('myplugincart/<pk>/<food_pk>/', customer.add_to_cart_plugin, name='add-to-cart-plugin'),
        
        path('pluscart/<pk>/', customer.plus_to_cart, name='plus-to-cart'),
        
        path('summary/<get_total>/<total_plugin>/<total_package>/', customer.OrderSummaryView, name='order-summary'),
        
        
        path('minus/<pk>', customer.minus_to_cart, name='minus-to-cart'),
        path('minusplugin/<pk>/<food_pk>/', customer.minus_to_cart_plugin, name='minus-to-cart-plugin'),
        
        
        
        
        
        
        
        path('delete/<pk>', customer.remove_from_cart, name='delete-item'),
        path('deleteplugin/<pk>/<food_pk>/', customer.remove_from_cart_plugin, name='plugin-delete-item'),
        
        
        path('receipt', customer.OrderReceipt, name='order-receipt'),
        path('done/<pk>', customer.SuccessPayment, name='success-payment'),
        
        path('payment/<paid_amount>/<mins>/<distance>/<delivery_amount>/<food_amount>/<tax_amount>/<package_amount>/', customer.verifyPayment, name='verify-payment'),
        
     

        path('subscriptionpayment/<amount>/<mins>/<distance>', customer.verifyPaymentOrderSubscription, name='subscription-verify-payment'),


        path('packagepayment/<pk>/<amount>/<mins>/<distance>', customer.verifyPaymentPackage, name='package-verify-payment'),

        path('myorder', customer.MyOrder, name='my-order'),

        path('paymentfailed', customer.closePayment, name='failed-payment'),

        path('packagepaymentfailed/<pk>', customer.closePackagePayment, name='failed-package-payment'),


        path('parcelsending', customer.ParcelMessage, name='parcel-message'),
        
        path("parcelpackage/<pk>", customer.ParcelPackageDetails, name="parcel-package"),
        

        path("paymentparcelpackage/<int:pk>/<int:id>/", customer.PackagePayment, name="payment-parcel-package"),
        

        path("paymentparcelpackage/<pk>/<distance>/<code>/", customer.verifyPaymentPackageSubscription, name="payment-parcel-package-subscription"),
        


        path("editparcel/<pk>/<id>/", customer.EditParcelMessage, name="edit-parcel-message"),

        path("editparcelpackage/<int:pk>/<int:id>/", customer.EditParcelPackageDetails, name="edit-parcel-package-message"),
        
        


        #path("search/", customer.SearchRestaurants.as_view(), name="search-results"),

       

        path('myaddress', customer.MyAddress, name='my-address'),


        path('addressdelete/<int:id>/', customer.DeleteAddress, name='delete-address'),

        path('editdelete/<id>', customer.EditAddress, name='edit-address'),

        path('payondelivery/<pk>/<amount>/<mins>/<distance>/<receiver_code>', customer.PayOnDelivery, name='pay-on-delivery'),


         path('finalpackagereceipt/<int:pk>/', customer.FinalPackageReceipt, name='final-receipt'),

        path('finalorderreceipt/<int:pk>/', customer.FinalOrdergeReceipt, name='final-order-receipt'),
         

        path('finalpackagereceipt/<int:pk>/<int:id>/', customer.DeletPackage, name='delete-package'),


        path('updatemyprofile/<username>/', customer.CustomerProfileUpdate, name='update-my-profile'),

        path('passwordupdate/', customer.ChangePassword, name='change-password'),


        path('subscriptionackagedetails/<pk>/', customer.SubscriptionPackageDetails, name='subscription-package'),


        
         #path('verifypaymentpackage/<pk>/', customer.verifyPaymentPackage, name='verify-payment-package'),


        path('checksubscription/', customer.CheckSubscription, name='check-subscription'),
        
        
        path('password_change/', customer.CustomPasswordChangeView.as_view(), name='password_change'),
        
        path('profile/update/', customer.UserProfileUpdateView, name='user-update'),


        path('posprinting/<int:pk>/', customer.PosPrinting, name='pos-print'),

        
        path('updatepackages/', customer.UpdatePackages, name='update-packages'),
        
        path('addonpackage/<pk>/', customer.AddonWithPackage, name='add-on-package'),
        
   
        
        

       
    ], 'app'), namespace='customer')),
]


htmx_urlpatterns = [

    path('checkusername/', general.CheckUsername, name="check-username"),
    path('checkemail/', general.CheckEmail, name="check-email"),
    path('loadvendor/', general.load_vendor, name='load-vendor'),
    
]

urlpatterns += htmx_urlpatterns

food/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app.views import general, customer, bike
from  django.contrib.auth import login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views







urlpatterns = [
    path('', include('app.urls')),
    #path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    #path('apiv1/', include('apiV1.urls')),
    #path('apiv2/', include('appV2.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup/customer/', customer.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/bike/', bike.BikeSignUpView.as_view(), name='bike_signup'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    path('accounts/', include('allauth.urls')),
    

    

]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

admin.site.site_header = "DeliveryGuy Admin"
admin.site.site_title = "DeliveryGuy Admin Portal"
admin.site.index_title = "Welcome to Delivery Admin Portal"





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "food.exception.handler404"

handler500 = "food.exception.handler500"

app/views/general.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import  auth, messages
from ..forms import *
from ..models import *
from django.contrib.auth import logout as django_logout
from difflib import SequenceMatcher
import datetime
from django.contrib.auth.decorators import login_required
import operator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, UpdateView, TemplateView)
from django.db.models import Count
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.utils.decorators import method_decorator
from ..decorators import customer_required
from django.views.decorators.http import require_http_methods
from compression_middleware.decorators import compress_page



class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


@compress_page
def FrontPage(request):
    current_time = datetime.datetime.now().strftime('%H:%M:%S')

    food = Good.objects.filter(available=True).filter(category__name='packages')
   
   
    advert = HomeAdvert.objects.filter(active=True).order_by('?')[:1]
    
    blog = BlogPost.objects.filter(active=True).order_by('-created_at')

    categories = Category.objects.all()
    goods_by_category = {}

    for category in categories:
        goods_by_category[category] = Good.objects.filter(category=category, available=True)


    
    #food = Good.objects.values('category__name').annotate(dcount=Count('category')).order_by('dcount')
    #print(food)

    sub = SubscriptionPackage.objects.filter()
    context = {'advert': advert, 'food': food, 'blog': blog, 'categories': categories, 'goods_by_category':goods_by_category, 'sub': sub}
    template_name = 'frontpage/index.html'
    return render(request, template_name, context)



def FoodDetails(request, name):
    template_name = 'general/details.html'
    good = get_object_or_404(Good, name=name)
    related = Good.objects.filter().exclude(name=name).order_by('?')[:3]
    context = {'good': good,'related': related}
    return render(request, template_name, context)


def load_vendor(request):
    city_id = request.GET.get('city')
    location = Location.objects.filter(city_id=city_id).order_by('name')
    return render(request, 'customer/vendors.html', {'location': location})






def login(request):
        
    advert = LoginAdvert.objects.filter(active=True).order_by('?')
    

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        if form.is_valid():
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                if request.user.is_customer:
                    return redirect('front_page')
                elif request.user.is_bike:
                    return redirect('bike:dashboard')
                                            
        
        else:
            args = {'form': form}
            return render(request, 'registration/login.html', args)

    else:
        form = AuthenticationForm

    args = {'form': form, 'advert': advert}
    return render(request, 'registration/login.html', args)






def CheckUsername(request):
    username = request.POST.get('username')
    if User.objects.filter(username=username).exists():
        return HttpResponse("<div style='color: red;'>The Username is Already Exits</div>")
    else:
        return HttpResponse("<div style='color: green;'>The Username is Available</div>") 
    

def CheckEmail(request):
    email = request.POST.get('email')
    if User.objects.filter(email=email).exists():
        return HttpResponse("The Email is Already Exits")
    else:
        return HttpResponse("The Email is Available")




def AllVendor(request, name):
     template_name = 'general/allvendor.html'
     vendor = Vendor.objects.filter(type__name=name)     
     context = {'vendor': vendor}     
     return render(request, template_name, context)
 
 
 
 
 


def BlogDetails(request, slug):
    blog = get_object_or_404(BlogPost, slug=slug)
    recent = BlogPost.objects.filter(active=True).exclude(slug=blog.slug)
    return render(request, 'general/blog_detail.html', {'blog': blog, 'recent': recent})

 
 
 
 

def logout_user(request):
    django_logout(request)
    return redirect('front_page')




def handler404(request, exception):
    context = {}
    response = render(request, "pages/errors/404.html", context=context)
    response.status_code = 404
    return response


def handler500(request):
    context = {}
    response = render(request, "pages/errors/500.html", context=context)
    response.status_code = 500
    return response

app/templates/general/blog_detail.html
{% extends 'frontpage/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load humanize %}
{% load mathfilters %}
{% load cart_template_tags %}
{% load multiplication_tag %}




{% include 'frontpage/nav2.html' %}


<!-- bredcrumb Area Start-->
<section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'app/assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'app/assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">
                    <h3>Our Blog
                    </h3>
                    <h1>{{ blog.title|upper|truncatechars:'30'}}
                    </h1>
                    <nav aria-label="breadcrumb">
                        <ul class="breadcrumb">
                          <li class="breadcrumb-item"><a href="/">Home</a></li>
                          <li class="breadcrumb-item active" aria-current="page">{{ blog.category.name }}</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- bredcrumb Area End --> 

   
 <!-- blog single start -->
 <div class="blog-single-area pd-top-120 pd-bottom-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-details-inner">
                    <div class="thumb pb-4">
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" width="100%">
                    </div> 
                    <span class="cat">
                        <span class="date">
                            <i class="ri-calendar-todo-fill"></i>{{ blog.created_date|naturalday }}
                        </span>
                        <a href="#" class="tag me-0">
                            <i class="ri-price-tag-3-fill"></i>{{ blog.category.name|upper }}
                        </a>
                    </span>                       
                    <h3>{{ blog.title|title }}</h3>
                    {{ blog.content|safe}}
                </div>
                <div class="tag-share-area">
                    <div class="row">
                        <div class="col-sm-6 align-self-center">
                            <div class="tag-inner">
                                <span>Tags: </span>
                               {% for tags in blog.tags.all %}
                                <a href="#">{{ tags.name }} </a>
                               {% endfor %} 
                              
                            </div>
                        </div>
                        <div class="col-sm-6 mt-3 mt-sm-0 align-items-center">
                            <ul class="social-area text-sm-end mt-md-0 mt-2">
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li> 
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fab fa-behance"></i></a></li> 
                                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li> 
                                <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li> 
                            </ul>
                        </div>
                    </div>
                </div>
               
              
            </div>
            <div class="col-lg-4">
                <div class="sidebar-area">
                    <div class="widget widget_search">
                        <form class="search-form">
                            <div class="form-group">
                                <input type="text" placeholder="Search your itmes">
                            </div>
                            <button class="submit-btn" type="submit"><i class="ri-search-line"></i></button>
                        </form>
                    </div>
                    <div class="widget widget-recent-post">
                        <h4 class="widget-title">Recent Post</h4>
                        <ul>
                            {% for tr in recent %}
                            <li>
                                <div class="media">
                                    <div class="media-left">
                                        <img src="{{ tr.image.url }}" alt="{{ tr.title }}" style="width:54px; length:49px">
                                    </div>
                                    <div class="media-body">
                                        <h6 class="title"><a href="{% url 'post-detail' tr.slug %}">{{ tr.title|truncatechars:'40' }}</a></h6>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                          
                        </ul>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
<!-- blog single end -->

  
{% endblock content %}

app/templates/general/details.html
{% extends 'frontpage/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load humanize %}
{% load mathfilters %}
{% load cart_template_tags %}
{% load multiplication_tag %}


{% include 'frontpage/nav2.html' %}

    <!-- shop-details Area Start-->
    <div class="shop-details-area pd-top-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="sticy-product">
                        <div class="product-thumbnail-wrapper">
                            <div class="single-thumbnail-slider">

                                <div class="slider-item">
                                    <img src="{{ good.image.url }}" alt="{{ good.name }} - Image">
                                </div>

                                {% for gallery_image in good.goodimagegallery_set.all %}
                                    
                                    <div class="slider-item">
                                        <img src="{{ gallery_image.image.url }}" alt="{{ good.name }} - Image">
                                    </div>
                                {% endfor %}

                                
                               
                            </div>
                            <div class="product-thumbnail-carousel">

                                <div class="single-thumbnail-item">
                                    <img src="{{ good.image.url }}" alt="{{ good.name }} - Image">
                                </div>

                                {% for gallery_image in good.goodimagegallery_set.all %}
                                 
                                    <div class="single-thumbnail-item">
                                        <img src="{{ gallery_image.image.url }}" alt="{{ good.name }} - Image">
                                    </div>
                                {% endfor %}

                                
                               
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="shop-item-details">
                        <nav>
                            <ul class="breadcrumb">
                              <li class="breadcrumb-item"><a href="/">Home</a></li>
                              <li class="breadcrumb-item"><a href="{% url 'app:all-menu' %}">All Menu</a></li>
                              <li class="breadcrumb-item active" aria-current="page">{{ good.name|upper }}</li>
                            </ul>
                        </nav>                        
                        <h2 class="entry-title">{{ good.name|upper }}</h2>
                        <div class="row">
                           
                            <div class="col-lg-6 align-self-center">
                                <h4 class="price">₦{{ good.price|floatformat:2|intcomma }}</h4>
                            </div>                            
                        </div>   

     


                        <p class="mt-4">{{ good.description|safe }}</p>  
                        
                        <form>
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus">
                                <input type="number" class="input-text qty text" step="1" min="1" max="10000" name="quantity" value="1">
                                <input type="button" value="+" class="plus">
                            </div>
                         
                            <a class="btn btn-secondary" href="{% url 'customer:add-to-cart' good.pk %}">Add to cart <i class="ri-add-line"></i></a>  

                        </form>
                       
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- shop-details Area End -->

    <!-- related-product Area Start-->
    <section class="related-product-area pd-top-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="section-title mb-0">
                        <h2 class="title">Related Products</h2>
                    </div>
                    <div class="related-product-slider owl-carousel style-2">
                        {% for rd in related  %}
                            <div class="item">
                                <div class="single-item-wrap">
                                    <div class="thumb">
                                        <img src="{{ rd.image.url }}" alt="{{ rd.name }}">
                                        <a class="fav-btn" href="#"><i class="ri-heart-line"></i></a>
                                    </div>
                                    <div class="wrap-details">
                                        <h5><a href="{% url 'app:food-general' rd.name %}">{{ rd.name|upper }}</a> <span class="price" style="margin-left: 10px;">₦{{ good.price|floatformat:2|intcomma }}</span></h5>
                                                                   
                                    </div>
                                    <div class="btn-area">
                                        <a class="btn btn-secondary" href="{% url 'app:food-general' rd.name %}">SEE DETAILS </a>         
                                    </div> 
                                </div>
                            </div>
                        {% endfor %}
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- related-product Area End -->

{% endblock content %}

app/templates/general/home.html
<h2>Sign up for a free account</h2>
<p class="lead">Select below the type of account you want to create</p>
<a href="{% url 'customer_signup' %}" class="btn btn-student btn-lg" role="button">I'm a Customer</a> <br/>
<a href="{% url 'bike_signup' %}" class="btn btn-teacher btn-lg" role="button">I'm a Bike</a>

app/templates/general/item_and_quantity_manager.html
{% if total_quantity == 0 %}                    
    <h6>{{ food_name|upper }} | ₦{{ food_price }} <span style="color: red; font-size: 12px"><a  class="button" hx-target="closest #id_item_and_quantity_manager" hx-post="{% url 'app:add-to-cart-plugin' plugin_food_pk good_pk %}"> ADD TO CART </a></span></h6>
{% else %}
    <h6>{{ food_name|upper }} ₦{{ food_price }} </h6>
    <div class="quantity1 buttons_added">
        <a hx-target="closest #id_item_and_quantity_manager" class="button"  hx-delete="{% url 'customer:minus-to-cart-plugin' plugin_food_pk good_pk %}"><input type="button" value="-" class="minus" style="color: #fff"></a>
        <input type="number" class="input-text qty text"  name="quantity" value="{{ total_quantity }}" style="color: #fff">
        <a hx-target="closest #id_item_and_quantity_manager" class="button"  hx-post="{% url 'customer:add-to-cart-plugin' plugin_food_pk good_pk %}"><input type="button" value="+" class="plus" style="color: #fff"></a>
        <a hx-target="closest #id_item_and_quantity_manager" class="button"  hx-delete="{% url 'customer:plugin-delete-item' plugin_food_pk good_pk %}"><input type="button" value="X" class="delete" style="color: #fff"></a>
    </div>
{% endif %}

app/templates/general/order_options.html
<option value="">---------</option>
{% for subcategories in subcategory %}
<option value="{{ subcategories.pk }}">{{ subcategories.name }}</option>
{% endfor %}