app/urls.py
from django.urls import include, path
from .views import general, customer, bike

urlpatterns = [

    path('', general.FrontPage, name='front_page'),
    
    path('logout', general.logout_user, name='user_logout'),
    path("login", general.login, name='userlogin'),
    path('vendorbytype/<name>/', general.AllVendor, name='all-vendors-type'),
    path('blogdetails/<slug>/', general.BlogDetails, name='post-detail'),
    
    


    path('bike/', include(([

        path('dashboard', bike.BikeDashboard, name='dashboard'),
        path('profile/<pk>', bike.BikeProfile, name='bike_profile'),
        path('orders', bike.DeliveryOrder, name='order_delivery'),
        path('ordersdetails/<pk>', bike.DetailsOrder, name='details'),
        path('orderaccept/<pk>', bike.AcceptOrder, name='accept-order'),
        path('ongoingmessage/<pk>/', bike.OnGoingOrder, name='order-ongoing'),
        
        
        path('packagecompleted/<pk>', bike.CompleteOrder, name='package-complete'),
        path('cancelpackage/<pk>', bike.CancelOrder, name='cancel-package'),
        
        path('messageaccept/<pk>/', bike.AcceptPackage, name='accept-message'),
        path('ongoingmessage/<pk>/', bike.OnGoingPackage, name='message-ongoing'),
        path('ongoingmessagedetails/<pk>/', bike.OnGoingPackageDetails, name='message-ongoing-details'),

      


   
      
    ], 'app'), namespace='bike')),

    path('customer/', include(([

        path('dashboard', customer.CustomerDashboard, name='dashboard'),
        path('profile/<pk>', customer.CustomerProfile, name='customer_profile'),
        path('vendors/', customer.AllRestaurants, name='all-vendor'),
        path('vendorgood/<pk>/', customer.AllVendorGoods, name='all-vendors-good'),

        path('menu/', customer.AllMenu, name='all-menu'),

        path('foodgeneral/<name>/', general.FoodDetails, name='food-general'),


        path('mycart/<pk>/', customer.add_to_cart, name='add-to-cart'),
        path('myplugincart/<pk>/<food_pk>/', customer.add_to_cart_plugin, name='add-to-cart-plugin'),
        
        path('pluscart/<pk>/', customer.plus_to_cart, name='plus-to-cart'),
        
        path('summary/<get_total>/<total_plugin>/<total_package>/', customer.OrderSummaryView, name='order-summary'),
        
        
        path('minus/<pk>', customer.minus_to_cart, name='minus-to-cart'),
        path('minusplugin/<pk>/<food_pk>/', customer.minus_to_cart_plugin, name='minus-to-cart-plugin'),
        
        
        
        
        
        
        
        path('delete/<pk>', customer.remove_from_cart, name='delete-item'),
        path('deleteplugin/<pk>/<food_pk>/', customer.remove_from_cart_plugin, name='plugin-delete-item'),
        
        
        path('receipt', customer.OrderReceipt, name='order-receipt'),
        path('done/<pk>', customer.SuccessPayment, name='success-payment'),
        
        path('payment/<paid_amount>/<mins>/<distance>/<delivery_amount>/<food_amount>/<tax_amount>/<package_amount>/', customer.verifyPayment, name='verify-payment'),
        
     

        path('subscriptionpayment/<amount>/<mins>/<distance>', customer.verifyPaymentOrderSubscription, name='subscription-verify-payment'),


        path('packagepayment/<pk>/<amount>/<mins>/<distance>', customer.verifyPaymentPackage, name='package-verify-payment'),

        path('myorder', customer.MyOrder, name='my-order'),

        path('paymentfailed', customer.closePayment, name='failed-payment'),

        path('packagepaymentfailed/<pk>', customer.closePackagePayment, name='failed-package-payment'),


        path('parcelsending', customer.ParcelMessage, name='parcel-message'),
        
        path("parcelpackage/<pk>", customer.ParcelPackageDetails, name="parcel-package"),
        

        path("paymentparcelpackage/<int:pk>/<int:id>/", customer.PackagePayment, name="payment-parcel-package"),
        

        path("paymentparcelpackage/<pk>/<distance>/<code>/", customer.verifyPaymentPackageSubscription, name="payment-parcel-package-subscription"),
        


        path("editparcel/<pk>/<id>/", customer.EditParcelMessage, name="edit-parcel-message"),

        path("editparcelpackage/<int:pk>/<int:id>/", customer.EditParcelPackageDetails, name="edit-parcel-package-message"),
        
        


        #path("search/", customer.SearchRestaurants.as_view(), name="search-results"),

       

        path('myaddress', customer.MyAddress, name='my-address'),


        path('addressdelete/<int:id>/', customer.DeleteAddress, name='delete-address'),

        path('editdelete/<id>', customer.EditAddress, name='edit-address'),

        path('payondelivery/<pk>/<amount>/<mins>/<distance>/<receiver_code>', customer.PayOnDelivery, name='pay-on-delivery'),


         path('finalpackagereceipt/<int:pk>/', customer.FinalPackageReceipt, name='final-receipt'),

        path('finalorderreceipt/<int:pk>/', customer.FinalOrdergeReceipt, name='final-order-receipt'),
         

        path('finalpackagereceipt/<int:pk>/<int:id>/', customer.DeletPackage, name='delete-package'),


        path('updatemyprofile/<username>/', customer.CustomerProfileUpdate, name='update-my-profile'),

        path('passwordupdate/', customer.ChangePassword, name='change-password'),


        path('subscriptionackagedetails/<pk>/', customer.SubscriptionPackageDetails, name='subscription-package'),


        
         #path('verifypaymentpackage/<pk>/', customer.verifyPaymentPackage, name='verify-payment-package'),


        path('checksubscription/', customer.CheckSubscription, name='check-subscription'),
        
        
        path('password_change/', customer.CustomPasswordChangeView.as_view(), name='password_change'),
        
        path('profile/update/', customer.UserProfileUpdateView, name='user-update'),


        path('posprinting/<int:pk>/', customer.PosPrinting, name='pos-print'),

        
        path('updatepackages/', customer.UpdatePackages, name='update-packages'),
        
        path('addonpackage/<pk>/', customer.AddonWithPackage, name='add-on-package'),
        
   
        
        

       
    ], 'app'), namespace='customer')),
]


htmx_urlpatterns = [

    path('checkusername/', general.CheckUsername, name="check-username"),
    path('checkemail/', general.CheckEmail, name="check-email"),
    path('loadvendor/', general.load_vendor, name='load-vendor'),
    
]

urlpatterns += htmx_urlpatterns

food/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app.views import general, customer, bike
from  django.contrib.auth import login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views







urlpatterns = [
    path('', include('app.urls')),
    #path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    #path('apiv1/', include('apiV1.urls')),
    #path('apiv2/', include('appV2.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup/customer/', customer.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/bike/', bike.BikeSignUpView.as_view(), name='bike_signup'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    path('accounts/', include('allauth.urls')),
    

    

]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

admin.site.site_header = "DeliveryGuy Admin"
admin.site.site_title = "DeliveryGuy Admin Portal"
admin.site.index_title = "Welcome to Delivery Admin Portal"





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "food.exception.handler404"

handler500 = "food.exception.handler500"

app/templates/customer/addcategory.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}
<style>
.btn-default{
background-color: #68889E;
color: red;
border-color: #2F3E48;
}
 
.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {
background-color: #2F3E48;
color:#FFF;
border-color: #31347B;
}

</style>

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>

                    <div class="myspace">
                    
                        <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase mt-1" target="_parent">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                        <a href="{% url 'customer:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow">Order History</a></br>
                    
                    </div>  

			    </div>
            </div>
            <div class="col-lg-8 col-md-5">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        
                        <div class="form-group col-sm-6">

                            <label>Pick Carteen, Store or Market</label>
                        
                            <select class="selectpicker" name='name' data-live-search="true">
                                
                                {% for c in category  %}

                                    <option value="{{ c.id }}" data-tokens="{{ c.name }}">{{ c.name|title }}</option>

                                {% endfor %}

                            </select>
                        
                        </div>

                        
                        <div id="bottom-wizard">
                            <button type="submit" name="process" class="btn btn-primary btn-lg btn-block">Proceed</button>
                        </div>
                    </form>
                </div>
                <!-- /Wizard container -->
                </div>
            </div><!-- /Row -->
        </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/customer/address.html
{% extends 'frontpage/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load humanize %}
{% load mathfilters %}
{% load cart_template_tags %}
{% load multiplication_tag %}


     


      <section class="offer-dedicated-body pt-2 pb-2 mt-4 mb-4">
         <div class="container">
            <div class="row">
               <div class="col-md-8">
                  {% for message in messages %}
                              <div class="alert alert-warning alert-dismissible fade show" role="alert">
                              <strong> {{ message }}!</strong>.
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                              </div>
                  {% endfor %}
                  <div class="offer-dedicated-body-left">
                     <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-order-online" role="tabpanel" aria-labelledby="pills-order-online-tab">
                           <div id="#menu" class="bg-white rounded shadow-sm p-4 mb-4 explore-outlets">
                              <h5 class="mb-4">Add My Location Information</h5>
                              <form class="explore-outlets-search mb-4" method="POST" enctype="multipart/form-data" novalidate="novalidate">
                                 {% csrf_token %}
                                 {{ form|crispy }}
                                 <div class="input-group">
                                    
                                       <div class="form-group col-md-12 mb-0">
                                          <button type="submit" class="btn btn-success btn-block btn-lg">Add Address
                                          <i class="icofont-long-arrow-right"></i></button><br/>
                                       </div>
                                 </div>
                              </form>
                              
                           </div>
                           
                        </div>
                        
                     </div>
                  </div>
               </div>
             
               <div class="col-md-4">
                  <div class="generator-bg rounded shadow-sm mb-4 p-4 osahan-cart-item">
                    
                     <div class="d-flex mb-4 osahan-cart-item-profile">
            
                        {% for order_item in user_order.items.all|slice:"1" %}
                        <img class="img-fluid mr-3 rounded-pill" alt="osahan" src="{{ order_item.item.vendor.picture.url }}">
                        <div class="d-flex flex-column">
                                <h6 class="mb-1 text-white">{{ order_item.item.name }}
                        </h6>
                        <p class="mb-0 text-white"><i class="icofont-location-pin"></i> {{ order_item.item.vendor.fulladdress|truncatechars:"40" }}</p>
                        </div>
                       {% endfor %}
            
                    </div>
            
                    <div class="bg-white rounded shadow-sm mb-2" style="padding-left: 10px; padding-right: 5px; padding-bottom: 5px; padding-top: 12px;"  >

                          {% for order_item in user_order.items.all %}

                           
                              <p style="margin-left: 10px; margin-right: 5px; margin-bottom: 5px; margin-top: 12px;" class="mb-2"><i class="icofont-ui-press text-danger food-item"></i> {{ order_item.item.name|title }}  x {{ order_item.quantity }}    <span class="float-right text-secondary">₦{{ order_item.get_total_item_price|floatformat:2|intcomma }}</span></p>
                              
                        
                           {% endfor %}

                     </div>

                  



					    
                       

                        {% if object is None %}
                              <div class="mb-2 bg-white rounded p-2 clearfix">
                                 <p class="mb-1">Item Total <span class="float-right text-dark">₦00.00</span></p>
                                 <p class="mb-1">Restaurant Charges <span class="float-right text-dark">₦00.00</span></p>
                                 <p class="mb-1">Delivery Fee <span class="text-info" data-toggle="tooltip" data-placement="top" title="Total discount breakup">
                                    <i class="icofont-info-circle"></i>
                                    </span> <span class="float-right text-dark">₦00.00</span>
                                 </p>
                                 <p class="mb-1 text-success">Total Discount 
                                    <span class="float-right text-success">₦00.00</span>
                                 </p>
                                 <hr />
                                 <h6 class="font-weight-bold mb-0">TO PAY  <span class="float-right">₦00.00</span></h6>
                              </div>
                        {% else %}


                              {% if object.shipping_address is None %}
                        
                                 <div class="mb-2 bg-white rounded p-2 clearfix">

                                          <p class="mb-1">Item Total <span class="float-right text-dark">₦{{ user_order.get_total_without_tax|floatformat:2|intcomma }}</span></p>
                                          <p class="mb-1">Total With VAT <span class="float-right text-dark">₦{{ user_order.get_tax_total|floatformat:2|intcomma }}</span></p>
                                          <p class="mb-1 text-success" style="color: red;">Kindly Enter Delivery Address</p>

                                 </div>

                              {% else %}

                                    <div class="mb-2 bg-white rounded p-2 clearfix">

                                       <p class="mb-1">Item Total <span class="float-right text-dark">₦{{ object.get_total_without_tax|floatformat:2|intcomma }}</span></p>
                                       <p class="mb-1">Total With VAT <span class="float-right text-dark">₦{{ object.get_tax_total|floatformat:2|intcomma }}</span></p>

                                       
                                       <p class="mb-1 text-success" style="color: red;">Delivery Details {{ distance.distance.text }} 
                                          
                                          {{ distance.duration.text|slice:':-4'|add:10 }}mins   

                                          {% if  distance.distance.text|slice:':-2'|mul:25 < 300.00 %}
                                                <span class="float-right text-success">₦400</span>
                                          {% else %}
                                                <span class="float-right text-success">₦{{  distance.distance.text|slice:':-2'|mul:35 }}</span>
                                          {% endif %}


                                       </p>


                                       
                                       {% if  distance.distance.text|slice:':-2'|mul:25 < 300.00 %}
                                                     
                                             {% with alpha=400 beta=object.get_tax_total|floatformat:0  %}
                                                <p class="mb-1 text-success">Total Delivery
                                                   <span class="float-right text-success">₦{{ alpha|addition:beta }}</span> 
                                                </p>
                                             {% endwith %}

                                       {% else %}


                                             {% with alpha=distance.distance.text|slice:':-2'|mul:35 beta=object.get_tax_total|floatformat:0  %}
                                                <p class="mb-1 text-success">Total Delivery 
                                                   <span class="float-right text-success">₦{{ alpha|addition:beta }}</span> 

                                                </p>
                                             {% endwith %}

                                       {% endif %}  

                                    


                                    <hr />

                                    {% if  distance.distance.text|slice:':-2'|mul:25 < 300.00 %}
                                       
                                          {% with alpha=400 beta=object.get_tax_total|floatformat:0  %}
                                             <h6 class="font-weight-bold mb-0">TOTAL<span class="float-right">₦{{ alpha|addition:beta }}</span></h6>
                                          {% endwith %}

                                    {% else %}

                                          {% with alpha=distance.distance.text|slice:':-2'|mul:35 beta=object.get_tax_total|floatformat:0  %}
                                                <h6 class="font-weight-bold mb-0">TOTAL<span class="float-right">₦{{ alpha|addition:beta }}</span></h6>
                                          {% endwith %}

                                    {% endif %}


                                 </div>

                                 {% if  distance.distance.text|slice:':-2'|mul:25 < 300.00 %}
                                                                                       

                                       {% with alpha=400 beta=object.get_tax_total|floatformat:0  %}
                                       
                                          <form>
                                             <script src="https://js.paystack.co/v1/inline.js"></script>
                                                <button class="btn btn-success btn-block btn-lg" type="button" onclick="payWithPaystack()" id="payment-submit">MAKE PAYMENT ₦{{ alpha|addition:beta }}<i class="icofont-plus"></i> </button></a>
                                          </form>

                                       {% endwith %}


                                 {% else %}

                                       {% with alpha=distance.distance.text|slice:':-2'|mul:35 beta=object.get_tax_total|floatformat:0  %}
                                          <form>
                                             <script src="https://js.paystack.co/v1/inline.js"></script>
                                             <button class="btn btn-success btn-block btn-lg" type="button" onclick="payWithPaystack()" id="payment-submit">MAKE PAYMENT ₦{{ alpha|addition:beta }}<i class="icofont-plus"></i> </button></a>

                                          </form>
                                       {% endwith %}


                  
                                 {% endif %}                                    

                              {% endif %}


                     {% endif %}


                    
                  </div>
				
				  
               </div>



            </div>
             
           </div>
         </div>
     </section> 

{% endblock content %}

app/templates/customer/checkoutcart.html
{% load humanize %}
{% load cart_template_tags %}



     
        


            <div class="sidebar-area">
                <div class="order-area">
                    <h5 class="title">Your order {{ request.user|cart_item_count }} items</h5>
                    {% for order_item in object.items.all %}
                        <div class="order-product">
                            <div class="thumb">
                                <img src="{{ order_item.item.image.url }}" alt="img">
                            </div>
                            <div class="details">
                                <h6>{{ order_item.item.name|title }} </h6>
                                <ul>
                                    <li><span>Price/Quanlity: </span>₦{{ order_item.item.price|floatformat:2|intcomma }}X {{ order_item.quantity}} =  ₦{{ order_item.get_total_item_price|floatformat:2|intcomma }}</li>
                                    <li><span>Quanlity: </span>{{ order_item.quantity}}</li>
                                </ul>

                            
                            </div>
                        </div>
                    {% endfor %}
                    <ul class="amount">
                        <li>Subtotal<span>₦{{ object.get_total_without_tax|floatformat:2|intcomma }}</span></li>
                        <li class="total">Total<span>₦{{ object.get_tax_total|floatformat:2|intcomma }}</span></li>
                    </ul>
                    
                    <a class="btn btn-secondary w-100" href="{% url 'customer:order-summary' %}"> PLACE ORDER</a>

                </div> 
            </div>

      

app/templates/customer/menu_backup.html
a








                    <div class="col-lg-9">
                        <div class="order-area">
                            <h5 class="title" style="color:#FAFAEF">OUR MENU</h5>
                            <div class="row">
                                {% for good in all_items %}
                                
                                <div class="col-md-4 col-sm-6 col-lg-3 mb-4">       
                                 
                                        <div class="card" style="margin-top: 11px;">
                                            <div class="card-image">
                                                <img src="{{ good.image.url }}" alt="{{ good.name}}">
                                            </div>
                                            <div class="card-body">

                                                <h2 style="font-size: 22px;">{{ good.name|upper }} </h2>
                                                
                                                   

                                                <span class="date" style="font-size: 14px; color: red;">
                                                   <a href="{% url 'customer:add-to-cart' good.pk %}">ADD TO CART</a> 
                                                </span>
                                                
                                               
                                                
                                            </div>
                                            <div class="card-footer">
                                                <div class="info">
                                                    <div class="value">₦{{ good.price }}</div>
                                                    <div class="type">PRICE</div>
                                                </div>
                                                <div class="info">
                                                    <div class="value">{{ good.stock }}</div>
                                                    <div class="type">QTY</div>
                                                </div>
                                                <div class="info">
                                                    <div class="value">4.5</div>
                                                    <div class="type">RATE </div>
                                                </div>
                                            </div>
                                        </div>
                                
                                
                                </div>


                                
                                      
                                    
                                {% endfor %}  
                            </div>
                        </div>              
                    </div>










                    plugins = OrderItem.objects.filter(ordered=False, user=request.user)
        plugin_items = plugins.plugin.all()
        plugin_items.update(ordered=True)
        for plugin in plugin_items:
            plugin.save()
            
            
        invoice = get_object_or_404(Order, ref_code__iexact=txref)
        order_items = invoice.items.all()
        order_items.update(ordered=True)
        for item in order_items:
            item.save()

app/templates/customer/successpayment.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    <div class="myspace">
                    
                        <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase mt-1" target="_parent">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                        <a href="{% url 'customer:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow">Order History</a></br>
                    
                    </div>  
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>

                        <h2 style="text-align: center;">Thanks! {{ request.user.username }} </h2>
                        <hr/>

                        <h3 style="text-align: center;">Your Payment Was Successful</h3><hr/>
                        <a href="{% url 'customer:order_history' request.user.id %}">
                            <p style="text-align: center;">View Your Order</p></a>
                            <p></p>
                   
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}